### ISSUE TITLE
nodejs error 

### ISSUE THREAD

**Issue by zkkzkk32312** [rayluo/github-pages-overwriter#6]
got this error when running the action/workflow 

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3

maybe need to use v4?

**Comment by rayluo** [comment]
Yes, please use v4 and report back. I'll update the README accordingly based on your test result. :)

**Comment by zkkzkk32312** [comment]
hey thanks for the quick reply, 
after using v4, 
I got an error with exit code 128.

no detail was given.

**Comment by rayluo** [comment]
> after using v4, I got an error with exit code 128.
> 
> no detail was given.

That is strange. How did you modify your workflow file? Note that [the `actions/checkout` usage is officially documented here](https://github.com/actions/checkout).

**Comment by zkkzkk32312** [comment]
im very new to github actions,
so its very possible its my own mistake,
but here is my current .yml:

name: Deploy Public Folder with GithubPageOverwriter

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Publish current workdir (which contains generated content) to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.3

        with:
          source-directory: ./public
          target-branch: gh-pages

**Comment by rayluo** [comment]
OK, so you are no longer seeing the initial "Node.js 16 ..." error. Then, your "actions/checkout@v4" change was good.

The "exit code 128" is an irrelevant error. You may try change your "./public" to "public" and retry.

**Comment by zkkzkk32312** [comment]
thanks for the info,
after modifying the line to : source-directory: public

I am still getting the exit code 128 error.

but using v4 was required to get rid of nodejs error for sure.

**Comment by rayluo** [comment]
You are hitting [this error](https://github.com/zkkzkk32312/IOTHouse/actions/runs/9276199048/job/25522709929#step:3:61). Honestly I am not sure where it came from. Can you double check whether you enabled github pages for your project already? That is like a prerequisite. You may refer to the "2. In your Github Pages setting, ..." paragraph in [GPO's readme](https://github.com/rayluo/github-pages-overwriter?tab=readme-ov-file#how-to-use-it).

**Comment by zkkzkk32312** [comment]
@rayluo hey thanks for pointing that out,
turns out I need to 

Check if "Read and write permissions" are enabled in Settings -> Actions -> General -> Workflow permissions:

**Comment by rayluo** [comment]
Thanks for sharing. Good to know. Presumably, adding the "permissions" and "contents: ..." lines as below might be able to also get it working WITHOUT checking that "Read and write permissions" setting. It could be a more deterministic pattern to ensure your future projects using GPO smoothly. You may give it a shot. :-)

    jobs:
      publish:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
          - name: Check out
            # You may use a newer version of https://github.com/actions/checkout
            uses: actions/checkout@v4
            ......
